### ISSUE TITLE
Error when running getting feedback.

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/hebi-matlab-api#16]
When running a demo using 1.5.1-SNAPSHOT I got this error message.  I was running in macOS Mojave, Matlab R2016b.  System was a 3-DoF arm running with fixed IP addresses using an Anker USB to Ethernet Adapter.

```matlab
Module did not respond with mac address!
Failed to parse an incoming message: us.hebi.sdk.lib.bm: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.
Module did not respond with mac address!
Module did not respond with mac address!
```

**Comment by ennerf** [comment]
Was there anything else on the network that may be acting weird? Maybe experimental retrofit snake firmware or some Android/iOS app development?

**Comment by daverolli** [comment]
Nope.  Modules running latest firmware doing the teach-repeat demo in Github.  Scope was also running at the same time, FWIW.

**Comment by daverolli** [comment]
Also what I pasted there was spewing continuously until quitting Matlab.  Not just a onetime error.

**Comment by ennerf** [comment]
Sorry for being embarrassed in front of a customer :(

I don't have a good guess on what would cause this. Can you reproduce it on your computer? Did it work correctly with an older API version?

**Comment by ennerf** [comment]
One thing I can do is to at least remove duplicate lines

**Comment by daverolli** [comment]
Trying to reproduce here with no luck at the moment.  Removing the duplicate lines over and over would at least help debugging if it comes up again.

**Comment by ennerf** [comment]
I'll also add the source IP address so we at least know where it came from

**Comment by ennerf** [comment]
The message was actually malformed, but I changed it to remove duplicate lines.
