### ISSUE TITLE
Groups are created with multiple modules if they have the same name.

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/hebi-matlab-api#22]
When you do `HebiLookup.newGroupFromNames()`, if there are multiple modules with the same family|name, a group is created with all of those modules.  I would expect behavior to probably throw and error saying that there were multiple modules found.  Behavior of the other APIs is to just use the first module that's found, which also isn't ideal, but is closer to expected behavior, and the debugging process brings you Scope / network debugging earlier.  If using a wild-card then multiple modules would be allowed.

This comes up a lot with the Mobile IO group creation if multiple people are on the same network with the default family|name.  We're partially fixing this by changing all the demos to require the user to change the family of the phone/iPad, so this low-ish priority for now.

**Comment by ennerf** [comment]
The MATLAB API used to select the first module, but we changed it after a discussion regarding wild-cards in individual names. If I understand correctly, the behavior you're suggesting is as follows:

Assuming there are 2 modules on the network named `HEBI | IO Board`

* `HebiLookup.newGroupFromNames('HEBI', 'IO Board')` should throw an error about a not uniquely identifiable name
* `HebiLookup.newGroupFromNames('*', 'IO Board')` should throw the same error
* `HebiLookup.newGroupFromNames('*', 'IO Boar?')` would return a group of two modules

**Comment by rLinks234** [comment]
From the initial discussion I overheard, Dave encountered an issue with the first example you provided @ennerf  (i.e., no wildcard patterns)

**Comment by ennerf** [comment]
I listed the suggested `future` behavior. The current behavior would be that it always creates a group with multiple modules.

**Comment by rLinks234** [comment]
No, what I mean happened that Dave tried to create a group like

`newGroupFromNames('HEBI', 'Mobile IO')` (no wildcard)
and he got a group with 2 modules - since we had 2 modules on the network with that name and family

**Comment by ennerf** [comment]
I understand what happened and why it is an issue. So what should the future behavior be?

Would everyone be happy if I implemented the behavior that I described above?

**Comment by daverolli** [comment]
Yup.  Behavior above is exactly right.

**Comment by ennerf** [comment]
Fixed in latest snapshot
