### ISSUE TITLE
Replace magic numbers when working with enums

### ISSUE THREAD

**Issue by ennerf** [HebiRobotics/hebi-matlab-api#29]
There are a lot of enum states that are expressed as numbers. They should be replaced with constant definitions, e.g., `HebiEnum.ARLowQuality`

**Comment by ennerf** [comment]
I added a snapshot with a `HebiEnum` class that contains constants for all enum states. Each field is documented via

`help HebiEnum.<property>`

![image](https://user-images.githubusercontent.com/5491587/61131883-8f815180-a4ba-11e9-9bae-2be372fbe8e2.png)

and in `doc HebiEnum`

![image](https://user-images.githubusercontent.com/5491587/61131956-b17ad400-a4ba-11e9-9729-f79491e7646d.png)

They are also referenced in the `unit` sections.

![image](https://user-images.githubusercontent.com/5491587/61132034-d66f4700-a4ba-11e9-9b72-e0fe8a4afd73.png)

I'm not sure whether the `*` really helps or whether I should just have the unit be `HebiEnum`

**Comment by daverolli** [comment]
Prob just `HebiEnum`?
