### ISSUE TITLE
Better error messages on HRDF parsing.

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/hebi-matlab-api#34]
In one case, I left off the `mass` parameter from a `<rigid-body>` type and it took a while to realize where the bug was, since the error in Matlab just showed:
```
Java exception occurred:
NullPointerException
```
Some of the parsing seems to return better error messages, like when multiplying rotation matrices for specifying rotations.  We were eventually able to track the source of this error down by looking at the errors returned by the C++ API.

**Comment by daverolli** [comment]
Running API 1.7

**Comment by ennerf** [comment]
There is a `required = true` flag, but maybe that doesn't get enforced properly. I'll look into it. Thanks for letting me know.

**Comment by ennerf** [comment]
added `rigid body does not define required 'mass'`. Will be live whenever the next release is out.
