### ISSUE TITLE
Imitation groups

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/hebi-matlab-api#4]
Imitation group for examples and unit tests.  Probably something that matches the C API.

**Comment by ennerf** [comment]
I finished most of the internals for this, so I'm thinking of the best way to add it to the API. For MATLAB I see 3 options:

1. `HebiUtils.newImitationGroup(numModules)`
 consistent with `newGroupFromLog`

2. `HebiLookup.newImitationGroup(numModules)`
 most easily accessible

3. `HebiGroup.newImitation(numModules)`
 matches C++ API

The order matches my personal preference. @daverolli any thoughts?

**Comment by rLinks234** [comment]
@ennerf I'd go with 1. In python, it's `hebi.util.create_imitation_group(size)`

**Comment by ennerf** [comment]
Added `HebiUtils.newImitationGroup(numModules)`. It's available in the latest snapshot
